POST http://localhost:8080/api/documents/move
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwibWVtYmVySWQiOjIsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3NDM2MzUwNTQsImV4cCI6MTc0MzYzNTk1NH0.WWJaz_Xskfew9IIxutjQOwr7ANaIvzGlItHHu_TECQA

{
  "fileId": 5,
  "isFolder": false,
  "parentFolderId": null,
  "order": 5,
  "isReallocate": false
}
