POST http://localhost:8080/api/documents/move
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibWVtYmVySWQiOjEsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3NDM5MzU5ODIsImV4cCI6MTc0NDEwODc4Mn0.Lh1LjrhINdTK_89wmkGfjWGprZqUJjNJ2zVlKOdHoQk

{
  "fileId": 6,
  "isFolder": false,
  "parentFolderId": 0,
  "order": 100,
  "isReallocate": false
}
