spring:
  # Flyway 비활성화
  flyway:
    enabled: false

  # 테스트용 H2 데이터베이스
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false

  # 메일 설정 (테스트용)
  mail:
    host: localhost
    port: 587
    username: test@example.com
    password: testpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# JWT 설정
jwt:
  secret: test-jwt-secret-key-for-testing-only-minimum-32-characters
  token-validity-in-seconds: 86400

# 카카오 설정 (테스트용)
kakao:
  client:
    id: test-kakao-client-id-for-testing

# Discord 웹훅 설정 (테스트용 더미 값)
discord:
  webhook:
    url: http://localhost:8080/test-webhook

# 서버 설정
server:
  port: 0
  shutdown: graceful

# 로깅 설정 (에러 로그 최소화)
logging:
  level:
    com.example.forever: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.context.support.AbstractApplicationContext: ERROR
    org.springframework.beans.factory.support.DefaultSingletonBeanRegistry: ERROR