name: image build and push

on:
  workflow_call:
    secrets:
      PROFILE:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REPO:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: 이미지 빌드하기

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.12.1"
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
          gradle-home-cache-excludes: |
            caches/build-cache-1
      - name: Run Jib
        id: build-image
        env:
          PROFILE: ${{ secrets.PROFILE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          IMAGE_TAG: ${{ github.sha }}

        run: ./BE/forever/gradlew jib
