name: Spring Boot CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - cicdtest

concurrency:
  group: ${{ github.ref }}

jobs:
  call-build-workflow:
    name: 이미지 빌드
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      PROFILE: ${{ secrets.PROFILE }}

  call-deploy-workflow:
    needs: call-build-workflow
    name: 서비스 배포
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      REPO: ${{ secrets.REPO }}
      WORKSPACE: ${{ secrets.WORKSPACE }}
      DEPLOY_SCRIPT: ${{ secrets.DEPLOY_SCRIPT }}
